{% set version = "1.2.7" %}
{% set min_python = "python >=3.6" %}

package:
  name: formulas-split
  version: {{ version }}

source:
  url: https://github.com/vinci1it2000/formulas/archive/v{{ version }}.tar.gz
  sha256: d61a7e2eadfce69183f6b69f8bb9f4ed5e14df2ace4ab91fd6717f85fcb3047a

build:
  noarch: python
  number: 0

requirements:
  host:
    - {{ min_python }}
  run:
    - {{ min_python }}

test:
  commands:
    - echo "tests in subpackages"

outputs:
  - name: formulas
    build:
      noarch: python
      script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
    requirements:
      host:
        - {{ min_python }}
        - pip
      run:
        - {{ min_python }}
        - numpy >=1.15
        - numpy-financial
        - python-dateutil
        - regex
        - schedula >=1.4.1
    test:
      requires:
        - pip
      imports:
        - formulas
      commands:
        - pip check

  - name: formulas-excel
    build:
      noarch: python
    requirements:
      host:
        - {{ min_python }}
      run:
        - {{ min_python }}
        - {{ pin_subpackage('formulas', exact=True) }}
        - dictdiffer
        - openpyxl
    test:
      requires:
        - pip
      imports:
        - formulas.excel
      commands:
        - pip check

  - name: formulas-plot
    build:
      noarch: python
    requirements:
      host:
        - {{ min_python }}
      run:
        - {{ min_python }}
        - {{ pin_subpackage('formulas', exact=True) }}
        - docutils
        - flask
        - jinja2
        - pygments
        - python-graphviz
    test:
      requires:
        - pip
      commands:
        - pip check

  - name: formulas-all
    build:
      noarch: python
    requirements:
      host:
        - {{ min_python }}
      run:
        - {{ min_python }}
        - {{ pin_subpackage('formulas-excel', exact=True) }}
        - {{ pin_subpackage('formulas-plot', exact=True) }}
    test:
      source_files:
        - test
      requires:
        - coverage
        - ddt
        - dill
        - pip
      commands:
        - pip check
        {% set cov_fail_under = 98 %}
        {% set delete_tests = [
          "test/test_readme.py",
          "test/test_setup.py",
        ] %}
        - python -c "import os; [os.unlink(p) for p in {{ delete_tests }}]"
        - coverage run --source=formulas --branch -m unittest discover --start-directory test --pattern 'test_*.py'
        - coverage report --show-missing --skip-covered --fail-under="{{ cov_fail_under }}"


about:
  home: https://github.com/vinci1it2000/formulas
  license: EUPL-1.1
  license_family: OTHER
  license_file: LICENSE.txt
  summary: Parse and compile Excel formulas and workbooks in python code.
  doc_url: https://formulas.readthedocs.io

extra:
  feedstock-name: formulas
  recipe-maintainers:
    - bollwyvl
