{% set version = "1.2.9" %}

{% set PYTHON = PYTHON | default("$PYTHON") %}

package:
  name: formulas
  version: {{ version }}

source:
  url: https://github.com/vinci1it2000/formulas/archive/v{{ version }}.tar.gz
  sha256: 38169a5bea62e76713089896b26f702315f6f90b770d8abe3e7389b7fc959bcc

build:
  number: 0
  noarch: python
  script:
    - python -c "import os; [os.unlink(f'test/test_{p}.py') for p in ['readme', 'setup']]"
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - numpy >=1.15
    - numpy-financial
    - python >={{ python_min }}
    - python-dateutil
    - regex
    - schedula >=1.4.1

test:
  requires:
    - pip
    - python {{ python_min }}
  imports:
    - formulas
  commands:
    - pip check

outputs:
  - name: formulas

  - name: formulas-excel
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage('formulas', max_pin="x.x.x") }}
        - dictdiffer
        - openpyxl
    test:
      requires:
        - pip
      imports:
        - formulas.excel
      commands:
        - pip check

  - name: formulas-plot
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage('formulas', max_pin="x.x.x") }}
        - docutils
        - flask
        - jinja2
        - pygments
        - python-graphviz
    test:
      requires:
        - pip
        - python {{ python_min }}
      commands:
        - pip check

  - name: formulas-all
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage('formulas-excel', max_pin="x.x.x") }}
        - {{ pin_subpackage('formulas-plot', max_pin="x.x.x") }}
    test:
      source_files:
        - test
      requires:
        - coverage
        - ddt
        - dill
        - pip
        - python {{ python_min }}
      commands:
        - pip check
        - coverage run --source=formulas --branch -m unittest discover --start-directory test --pattern 'test_*.py'
        - coverage report --show-missing --skip-covered --fail-under=98

about:
  home: https://github.com/vinci1it2000/formulas
  license: EUPL-1.1
  license_family: OTHER
  license_file: LICENSE.txt
  summary: Parse and compile Excel formulas and workbooks in python code.
  doc_url: https://formulas.readthedocs.io

extra:
  feedstock-name: formulas
  recipe-maintainers:
    - bollwyvl
