{% set version = "1.2.8" %}
{% set min_python = "python >=3.6" %}

# handle undefined PYTHON in `noarch: generic` outputs
{% if PYTHON is not defined %}{% set PYTHON = "$PYTHON" %}{% endif %}

package:
  name: formulas
  version: {{ version }}

source:
  url: https://github.com/vinci1it2000/formulas/archive/v{{ version }}.tar.gz
  sha256: 5c7232c164d9aedba50bb2897d234069a56c06e1d4f9decb169de3257d2b0ffb

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - numpy >=1.15
    - numpy-financial
    - python >=3.6
    - python-dateutil
    - regex
    - schedula >=1.4.1

test:
  requires:
    - pip
  imports:
    - formulas
  commands:
    - pip check

outputs:
  - name: formulas

  - name: formulas-excel
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage('formulas', max_pin="x.x.x") }}
        - dictdiffer
        - openpyxl
    test:
      requires:
        - pip
      imports:
        - formulas.excel
      commands:
        - pip check

  - name: formulas-plot
    build:
      noarch: python
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage('formulas', max_pin="x.x.x") }}
        - docutils
        - flask
        - jinja2
        - pygments
        - python-graphviz
    test:
      requires:
        - pip
      commands:
        - pip check

  - name: formulas-all
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage('formulas-excel', max_pin="x.x.x") }}
        - {{ pin_subpackage('formulas-plot', max_pin="x.x.x") }}
    test:
      source_files:
        - test
      requires:
        - coverage
        - ddt
        - dill
        - pip
      commands:
        - pip check
        {% set cov_fail_under = 98 %}
        {% set delete_tests = [
          "test/test_readme.py",
          "test/test_setup.py",
        ] %}
        - python -c "import os; [os.unlink(p) for p in {{ delete_tests }}]"
        - coverage run --source=formulas --branch -m unittest discover --start-directory test --pattern 'test_*.py'
        - coverage report --show-missing --skip-covered --fail-under="{{ cov_fail_under }}"

about:
  home: https://github.com/vinci1it2000/formulas
  license: EUPL-1.1
  license_family: OTHER
  license_file: LICENSE.txt
  summary: Parse and compile Excel formulas and workbooks in python code.
  doc_url: https://formulas.readthedocs.io

extra:
  feedstock-name: formulas
  recipe-maintainers:
    - bollwyvl
